services:
  mysql:
    image: mysql:8.0
    container_name: mysql_proyecto
    environment:
      MYSQL_DATABASE: proyecto_11
      MYSQL_USER: nombre_1
      MYSQL_PASSWORD: contra_1
      MYSQL_ROOT_PASSWORD: contra_1
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

